/**
 * DEMO verisi — Şartname 37: "Mock veri yalnızca geliştirme ve demo
 * ortamında kullanılmalıdır. Demo için kurgusal sanatçı profilleri kullan."
 *
 * Buradaki bütün sanatçılar, kullanıcılar ve içerikler tamamen kurgusaldır.
 * Görseller telifsiz, kod ile üretilmiş SVG dosyalarıdır (public/demo/).
 */

import type {
  Artist,
  ArtistApplication,
  ArtistFollow,
  ArtistMember,
  AuditLog,
  FeatureFlags,
  Notification,
  Post,
  PostLike,
  PostMedia,
  Profile,
  Report,
} from "@/types";

const now = Date.now();
const h = (hours: number) => new Date(now - hours * 3600_000).toISOString();
const d = (days: number) => h(days * 24);
const future = (days: number) => new Date(now + days * 24 * 3600_000).toISOString();

/* ---------- Kullanıcılar ---------- */

export const demoProfiles: Profile[] = [
  {
    id: "u-demo-user",
    username: "dinleyici.06",
    display_name: "Deniz",
    avatar_path: "/demo/avatars/user.svg",
    role: "user",
    account_status: "active",
    email_verified: true,
    locale: "tr-TR",
    timezone: "Europe/Istanbul",
    marketing_consent: false,
    last_seen_at: h(1),
    created_at: d(120),
    updated_at: d(2),
    deleted_at: null,
  },
  {
    id: "u-demo-artist",
    username: "rayvold",
    display_name: "Ray Vold",
    avatar_path: "/demo/artists/rayvold-avatar.svg",
    role: "artist",
    account_status: "active",
    email_verified: true,
    locale: "tr-TR",
    timezone: "Europe/Istanbul",
    marketing_consent: true,
    last_seen_at: h(3),
    created_at: d(300),
    updated_at: d(1),
    deleted_at: null,
  },
  {
    id: "u-demo-mod",
    username: "gozcu",
    display_name: "Gözcü",
    avatar_path: "/demo/avatars/mod.svg",
    role: "moderator",
    account_status: "active",
    email_verified: true,
    locale: "tr-TR",
    timezone: "Europe/Istanbul",
    marketing_consent: false,
    last_seen_at: h(6),
    created_at: d(200),
    updated_at: d(10),
    deleted_at: null,
  },
  {
    id: "u-demo-admin",
    username: "kurucu",
    display_name: "Kurucu",
    avatar_path: "/demo/avatars/admin.svg",
    role: "super_admin",
    account_status: "active",
    email_verified: true,
    locale: "tr-TR",
    timezone: "Europe/Istanbul",
    marketing_consent: false,
    last_seen_at: h(0.5),
    created_at: d(400),
    updated_at: d(0.5),
    deleted_at: null,
  },
  {
    id: "u-applicant",
    username: "sokak.sairi",
    display_name: "Sokak Şairi",
    avatar_path: "/demo/avatars/applicant.svg",
    role: "user",
    account_status: "active",
    email_verified: true,
    locale: "tr-TR",
    timezone: "Europe/Istanbul",
    marketing_consent: true,
    last_seen_at: d(1),
    created_at: d(40),
    updated_at: d(1),
    deleted_at: null,
  },
];

/* ---------- Kurgusal sanatçılar ---------- */

const baseTheme = {
  background_mode: "gradient" as const,
  background_texture: "grain" as const,
  hero_overlay_strength: 0.55,
  card_style: "soft" as const,
  heading_style: "display" as const,
  motion_intensity: "medium" as const,
};

export const demoArtists: Artist[] = [
  {
    id: "a-rayvold",
    stage_name: "Ray Vold",
    slug: "rayvold",
    short_bio: "Gece trafiğinde yazılan şarkılar. İstanbul'un batı yakasından sinyaller.",
    long_bio:
      "Ray Vold, 2018'den beri kendi kayıt düzeninde üreten, sözlerini şehir gözlemleri üzerine kuran bir sanatçı. İlk dönem çalışmalarını mahalle stüdyolarında kaydetti; bugün kendi ekibiyle bağımsız yayın yapıyor. RapLab'de stüdyo günlüklerini, kapak süreçlerini ve çıkacak projelerin perde arkasını paylaşıyor.",
    city: "İstanbul",
    genres: ["alternatif rap", "boom bap"],
    profile_image_path: "/demo/artists/rayvold-avatar.svg",
    desktop_cover_path: "/demo/artists/rayvold-cover.svg",
    mobile_cover_path: "/demo/artists/rayvold-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#ff4d5a", secondary_color: "#2b3a67" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 48210,
    owner_user_id: "u-demo-artist",
    created_at: d(300),
    updated_at: h(4),
    suspended_at: null,
  },
  {
    id: "a-nefes",
    stage_name: "Nefes",
    slug: "nefes",
    short_bio: "Az kelime, çok ağırlık. Ankara underground'ının sakin sesi.",
    long_bio:
      "Nefes, minimal prodüksiyonlar üzerine kurduğu anlatımıyla tanınır. Sahne dışında az görünür; sözü kayıtlarına bırakır. RapLab sayfası, dinleyicileriyle kurduğu tek resmî iletişim kanalıdır.",
    city: "Ankara",
    genres: ["lo-fi rap", "spoken word"],
    profile_image_path: "/demo/artists/nefes-avatar.svg",
    desktop_cover_path: "/demo/artists/nefes-cover.svg",
    mobile_cover_path: "/demo/artists/nefes-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#4da3ff", secondary_color: "#1d2b3a", card_style: "sharp" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 23480,
    owner_user_id: "u-demo-artist",
    created_at: d(260),
    updated_at: h(20),
    suspended_at: null,
  },
  {
    id: "a-karga",
    stage_name: "Karga",
    slug: "karga",
    short_bio: "Çatılardan bakınca şehir başka. İzmir'den sert vuruşlar.",
    long_bio:
      "Karga, drill ve trap altyapılarını Ege ağzıyla birleştiren üretken bir isim. Video estetiğine verdiği önemle biliniyor; her klibinin yönetmen koltuğunda kendisi oturuyor.",
    city: "İzmir",
    genres: ["drill", "trap"],
    profile_image_path: "/demo/artists/karga-avatar.svg",
    desktop_cover_path: "/demo/artists/karga-cover.svg",
    mobile_cover_path: "/demo/artists/karga-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#9d6bff", secondary_color: "#241a3d", motion_intensity: "high" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 61930,
    owner_user_id: "u-demo-artist",
    created_at: d(220),
    updated_at: h(2),
    suspended_at: null,
  },
  {
    id: "a-semak",
    stage_name: "Sema K",
    slug: "sema-k",
    short_bio: "Kadıköy sahnesinin yeni nesli. Melodik rap, keskin kalem.",
    long_bio:
      "Sema K, melodik rap ile klasik söz yazımını aynı masada buluşturuyor. İlk EP'si bağımsız listelerde uzun süre kaldı; şimdi ilk albümünün geri sayımını RapLab üzerinden paylaşıyor.",
    city: "İstanbul",
    genres: ["melodik rap", "r&b"],
    profile_image_path: "/demo/artists/semak-avatar.svg",
    desktop_cover_path: "/demo/artists/semak-cover.svg",
    mobile_cover_path: "/demo/artists/semak-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#e8b64c", secondary_color: "#3a2d1d", heading_style: "classic" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 35770,
    owner_user_id: "u-demo-artist",
    created_at: d(180),
    updated_at: h(30),
    suspended_at: null,
  },
  {
    id: "a-golge06",
    stage_name: "Gölge 06",
    slug: "golge-06",
    short_bio: "Ankara'nın soğuğu sözlere işledi. Boom bap'in yerli hali.",
    long_bio:
      "Gölge 06, on yılı aşkın süredir sahnede. Eski toprak sayılır ama üretimi hiç yavaşlamadı. RapLab'de arşivinden hikâyeler ve yeni nesle notlar paylaşıyor.",
    city: "Ankara",
    genres: ["boom bap", "klasik rap"],
    profile_image_path: "/demo/artists/golge-avatar.svg",
    desktop_cover_path: "/demo/artists/golge-cover.svg",
    mobile_cover_path: "/demo/artists/golge-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#58d68d", secondary_color: "#15352a", card_style: "round", motion_intensity: "low" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 90140,
    owner_user_id: "u-demo-artist",
    created_at: d(350),
    updated_at: d(3),
    suspended_at: null,
  },
  {
    id: "a-beton",
    stage_name: "Beton Çiçeği",
    slug: "beton-cicegi",
    short_bio: "Adana sıcağında büyüyen sesler. Yeni doğrulandı, yeni başlıyor.",
    long_bio:
      "Beton Çiçeği, güneyin genç kolektifinden çıkan bir solo proje. RapLab doğrulamasını yeni aldı; ilk resmî paylaşımlarını burada yapıyor.",
    city: "Adana",
    genres: ["trap", "alternatif"],
    profile_image_path: "/demo/artists/beton-avatar.svg",
    desktop_cover_path: "/demo/artists/beton-cover.svg",
    mobile_cover_path: "/demo/artists/beton-cover-mobile.svg",
    theme_config: { ...baseTheme, accent_color: "#ff8a5c", secondary_color: "#3d241a" },
    verification_status: "approved",
    profile_status: "active",
    follower_count: 4180,
    owner_user_id: "u-demo-artist",
    created_at: d(9),
    updated_at: h(10),
    suspended_at: null,
  },
];

/* ---------- Ekip üyelikleri ---------- */

export const demoMembers: ArtistMember[] = demoArtists.map((a) => ({
  id: `m-${a.id}`,
  artist_id: a.id,
  user_id: "u-demo-artist",
  member_role: "owner",
  permissions: [
    "manage_posts",
    "publish_posts",
    "delete_posts",
    "manage_media",
    "manage_profile",
    "view_analytics",
    "manage_team",
    "manage_projects",
  ],
  status: "active",
  invited_by: "u-demo-artist",
  accepted_at: a.created_at,
  created_at: a.created_at,
  updated_at: a.created_at,
}));

demoMembers.push({
  id: "m-rayvold-manager",
  artist_id: "a-rayvold",
  user_id: "u-applicant",
  member_role: "manager",
  permissions: ["manage_posts", "publish_posts", "manage_media", "view_analytics"],
  status: "active",
  invited_by: "u-demo-artist",
  accepted_at: d(30),
  created_at: d(31),
  updated_at: d(30),
});

/* ---------- Gönderiler ---------- */

function post(p: Partial<Post> & Pick<Post, "id" | "artist_id" | "post_type">): Post {
  return {
    author_user_id: "u-demo-artist",
    title: null,
    body: null,
    visibility: "public",
    status: "published",
    is_pinned: false,
    like_count: 0,
    view_count: 0,
    allow_external_share: true,
    notify_followers: true,
    scheduled_at: null,
    published_at: h(1),
    edited_at: null,
    created_at: h(1),
    updated_at: h(1),
    deleted_at: null,
    meta: null,
    ...p,
  };
}

export const demoPosts: Post[] = [
  post({
    id: "p-rv-pinned",
    artist_id: "a-rayvold",
    post_type: "announcement",
    title: "『GECE TRAFİĞİ』 — Yeni albüm süreci resmen başladı",
    body: "Uzun zamandır sakladığım haberi vermenin vakti geldi. Üçüncü stüdyo albümünün kayıtları bitti, miks aşamasındayız. Bu sayfada süreci adım adım paylaşacağım. Sabırla bekleyen herkese teşekkürler.",
    is_pinned: true,
    like_count: 12470,
    view_count: 88450,
    published_at: d(6),
    created_at: d(6),
    updated_at: d(6),
    meta: { status_label: "Albüm süreci", event_date: future(21) },
  }),
  post({
    id: "p-rv-countdown",
    artist_id: "a-rayvold",
    post_type: "countdown",
    title: "İlk single'a geri sayım",
    body: "Albümün ilk teklisi bütün platformlarda aynı anda. Saat gece yarısı.",
    like_count: 8931,
    view_count: 54210,
    published_at: d(2),
    created_at: d(2),
    updated_at: d(2),
    meta: { countdown_ends_at: future(9) },
  }),
  post({
    id: "p-rv-studio",
    artist_id: "a-rayvold",
    post_type: "image",
    title: null,
    body: "Miks odasından bir kare. Bu kayıtta analog masaya döndük; farkı kulaklarınız duyacak.",
    like_count: 5204,
    view_count: 31890,
    published_at: h(5),
    created_at: h(5),
    updated_at: h(5),
  }),
  post({
    id: "p-rv-teaser",
    artist_id: "a-rayvold",
    post_type: "audio_teaser",
    title: "『GECE TRAFİĞİ』 intro — 30 saniyelik önizleme",
    body: "Albümün açılışından küçük bir bölüm. Devamı yakında.",
    like_count: 15883,
    view_count: 92610,
    published_at: h(22),
    created_at: h(22),
    updated_at: h(22),
  }),
  post({
    id: "p-nf-text",
    artist_id: "a-nefes",
    post_type: "text",
    body: "Bazen bir kayıt bir yılda oturur, bazen bir gecede. İkisi de aynı derecede doğrudur. Acele eden sese güvenmeyin.",
    like_count: 3120,
    view_count: 19870,
    published_at: h(9),
    created_at: h(9),
    updated_at: h(9),
  }),
  post({
    id: "p-nf-followers",
    artist_id: "a-nefes",
    post_type: "text",
    title: "Takipçilere özel not",
    body: "Bu ayki kapalı kayıt oturumunun tarihi belli oldu. Detaylar yalnızca burada: 24'ü akşamı, her zamanki yerde. Bilenler bilir.",
    visibility: "followers",
    like_count: 842,
    view_count: 4310,
    published_at: d(1),
    created_at: d(1),
    updated_at: d(1),
  }),
  // Video işleme hattını dürüstçe gösteren örnek: medya "processing"
  // durumundayken gönderi yayımlanamaz (Değişmez Kural 15, Şartname 8.2)
  post({
    id: "p-kg-video",
    artist_id: "a-karga",
    post_type: "video",
    title: "『ÇATI』 klip — kamera arkası",
    body: "Üç gece, iki çatı, tek plan. Klibin tamamı cuma günü.",
    status: "processing",
    published_at: null,
    like_count: 0,
    view_count: 0,
    created_at: h(3),
    updated_at: h(3),
  }),
  post({
    id: "p-kg-gallery",
    artist_id: "a-karga",
    post_type: "gallery",
    title: "Set fotoğrafları",
    body: "Klip setinden seçtiklerim. Işığı doğal bıraktık.",
    like_count: 4180,
    view_count: 28840,
    published_at: d(4),
    created_at: d(4),
    updated_at: d(4),
  }),
  post({
    id: "p-sk-countdown",
    artist_id: "a-semak",
    post_type: "countdown",
    title: "『KIYI』 — ilk albüm",
    body: "İlk albümüm KIYI için geri sayım başladı. Bu yolculuk hepimizin.",
    is_pinned: true,
    like_count: 11240,
    view_count: 71230,
    published_at: d(3),
    created_at: d(3),
    updated_at: d(3),
    meta: { countdown_ends_at: future(16) },
  }),
  post({
    id: "p-sk-image",
    artist_id: "a-semak",
    post_type: "image",
    body: "Albüm kapağı çekimlerinden. Deniz kenarında dört saat bekledik, o ışık geldi.",
    like_count: 6832,
    view_count: 41560,
    published_at: h(16),
    created_at: h(16),
    updated_at: h(16),
  }),
  post({
    id: "p-gl-archive",
    artist_id: "a-golge06",
    post_type: "text",
    title: "Arşivden: ilk demo kaydım (2009)",
    body: "Bugün eski hard diski karıştırırken 2009'daki ilk demoyu buldum. Mikrofon, yorgan, umut. Hepsi bu kadardı. Yeni başlayanlara: ekipman bahane, söz esas.",
    like_count: 18220,
    view_count: 104300,
    published_at: d(2),
    created_at: d(2),
    updated_at: d(2),
  }),
  post({
    id: "p-gl-project",
    artist_id: "a-golge06",
    post_type: "project",
    title: "『06 ARŞİV』 projesi duyurusu",
    body: "Eski kayıtları restore edip tek çatı altında topluyorum. 15 yıllık arşiv, ilk kez düzenli bir seri hâlinde.",
    like_count: 7431,
    view_count: 39980,
    published_at: d(5),
    created_at: d(5),
    updated_at: d(5),
    meta: { status_label: "Devam ediyor" },
  }),
  post({
    id: "p-bt-first",
    artist_id: "a-beton",
    post_type: "text",
    title: "İlk gönderi",
    body: "RapLab doğrulaması geldi. Buradan ilk mesaj: güneyden yeni sesler geliyor, hazır olun.",
    like_count: 1244,
    view_count: 8120,
    published_at: h(10),
    created_at: h(10),
    updated_at: h(10),
  }),
  post({
    id: "p-rv-draft",
    artist_id: "a-rayvold",
    post_type: "text",
    title: "Taslak: kapak hikâyesi",
    body: "Kapak fotoğrafının hikâyesini anlatacağım gönderi taslağı...",
    status: "draft",
    published_at: null,
    like_count: 0,
    view_count: 0,
    created_at: h(7),
    updated_at: h(7),
  }),
  post({
    id: "p-rv-scheduled",
    artist_id: "a-rayvold",
    post_type: "announcement",
    title: "Dinleme etkinliği duyurusu",
    body: "Albüm çıkmadan önce kapalı bir dinleme etkinliği yapıyoruz. Yer ve tarih bu gönderiyle açıklanacak.",
    status: "scheduled",
    scheduled_at: future(3),
    published_at: null,
    like_count: 0,
    view_count: 0,
    created_at: h(12),
    updated_at: h(12),
  }),
];

/* ---------- Gönderi medyaları ---------- */

export const demoMedia: PostMedia[] = [
  {
    id: "md-rv-studio",
    post_id: "p-rv-studio",
    media_type: "image",
    bucket_name: "post-media",
    storage_path: "/demo/posts/rayvold-studio.svg",
    mime_type: "image/svg+xml",
    file_size_bytes: 21400,
    width: 1600,
    height: 1000,
    duration_seconds: null,
    alt_text: "Loş bir miks odasında analog ses masası ve kırmızı kayıt ışığı",
    poster_path: null,
    waveform_data: null,
    processing_status: "ready",
    sort_order: 0,
    checksum: "demo-checksum-1",
    created_at: h(5),
  },
  {
    id: "md-rv-teaser",
    post_id: "p-rv-teaser",
    media_type: "audio",
    bucket_name: "post-media",
    storage_path: "/demo/audio/teaser.wav",
    mime_type: "audio/wav",
    file_size_bytes: 480000,
    width: null,
    height: null,
    duration_seconds: 30,
    alt_text: null,
    poster_path: null,
    waveform_data: [
      0.2, 0.5, 0.8, 0.6, 0.9, 0.4, 0.7, 1, 0.8, 0.5, 0.3, 0.6, 0.9, 0.7, 0.4, 0.8,
      0.6, 1, 0.7, 0.5, 0.9, 0.6, 0.3, 0.7, 0.8, 0.5, 0.9, 0.6, 0.4, 0.7, 0.5, 0.2,
    ],
    processing_status: "ready",
    sort_order: 0,
    checksum: "demo-checksum-2",
    created_at: h(22),
  },
  {
    id: "md-kg-video",
    post_id: "p-kg-video",
    media_type: "video",
    bucket_name: "post-media",
    storage_path: "/demo/video/placeholder.mp4",
    mime_type: "video/mp4",
    file_size_bytes: 8200000,
    width: 1280,
    height: 720,
    duration_seconds: 42,
    alt_text: null,
    poster_path: "/demo/posts/karga-video-poster.svg",
    waveform_data: null,
    processing_status: "processing",
    sort_order: 0,
    checksum: "demo-checksum-3",
    created_at: h(3),
  },
  ...[0, 1, 2, 3].map((i) => ({
    id: `md-kg-gallery-${i}`,
    post_id: "p-kg-gallery",
    media_type: "image" as const,
    bucket_name: "post-media",
    storage_path: `/demo/posts/karga-set-${i + 1}.svg`,
    mime_type: "image/svg+xml",
    file_size_bytes: 18000,
    width: 1200,
    height: 1200,
    duration_seconds: null,
    alt_text: `Klip setinden kare ${i + 1}: çatıda gece çekimi`,
    poster_path: null,
    waveform_data: null,
    processing_status: "ready" as const,
    sort_order: i,
    checksum: `demo-checksum-g${i}`,
    created_at: d(4),
  })),
  {
    id: "md-sk-cover",
    post_id: "p-sk-image",
    media_type: "image",
    bucket_name: "post-media",
    storage_path: "/demo/posts/semak-kiyi.svg",
    mime_type: "image/svg+xml",
    file_size_bytes: 19800,
    width: 1600,
    height: 1000,
    duration_seconds: null,
    alt_text: "Gün batımında deniz kıyısında albüm kapağı çekimi",
    poster_path: null,
    waveform_data: null,
    processing_status: "ready",
    sort_order: 0,
    checksum: "demo-checksum-4",
    created_at: h(16),
  },
];

/* ---------- Beğeni ve takipler (demo kullanıcı) ---------- */

export const demoLikes: PostLike[] = [
  { post_id: "p-gl-archive", user_id: "u-demo-user", created_at: d(1) },
  { post_id: "p-rv-teaser", user_id: "u-demo-user", created_at: h(20) },
];

export const demoFollows: ArtistFollow[] = [
  { artist_id: "a-rayvold", user_id: "u-demo-user", created_at: d(90) },
  { artist_id: "a-golge06", user_id: "u-demo-user", created_at: d(60) },
  { artist_id: "a-semak", user_id: "u-demo-user", created_at: d(20) },
];

/* ---------- Sanatçı başvuruları ---------- */

export const demoApplications: ArtistApplication[] = [
  {
    id: "app-1",
    user_id: "u-applicant",
    stage_name: "Sokak Şairi",
    legal_name: "(kurgusal başvuru)",
    contact_email: "demo@raplab.local",
    phone_optional: null,
    artist_description:
      "Beş yıldır sokak performansları yapıyorum, iki EP yayımladım. RapLab'de resmî sayfamı açmak istiyorum.",
    official_social_links: ["https://ornek.sosyal/sokaksairi"],
    distribution_links: ["https://ornek.dagitim/sokaksairi"],
    label_name_optional: null,
    applicant_relationship: "artist",
    identity_document_path: "verification-docs/app-1/kimlik.pdf",
    authorization_document_path: null,
    voice_declaration_path: "verification-docs/app-1/beyan.webm",
    identity_viewed_at: null,
    identity_viewed_by: null,
    rights_declaration: true,
    additional_notes: null,
    status: "under_review",
    review_note: null,
    created_at: d(3),
    updated_at: d(1),
  },
  {
    id: "app-2",
    user_id: "u-demo-user",
    stage_name: "Ekho",
    legal_name: "(kurgusal başvuru)",
    contact_email: "demo2@raplab.local",
    phone_optional: null,
    artist_description: "Yeni nesil prodüktör/rapçi. Kataloğum ekte.",
    official_social_links: [],
    distribution_links: [],
    label_name_optional: "Bağımsız",
    applicant_relationship: "artist",
    identity_document_path: null,
    authorization_document_path: null,
    voice_declaration_path: null,
    identity_viewed_at: null,
    identity_viewed_by: null,
    rights_declaration: true,
    additional_notes: "Kimlik belgesini bu hafta yükleyeceğim.",
    status: "more_information_required",
    review_note: "Kimlik belgesi eksik. Yüklendiğinde inceleme devam edecek.",
    created_at: d(8),
    updated_at: d(2),
  },
];

/* ---------- Raporlar ---------- */

export const demoReports: Report[] = [
  {
    id: "r-1",
    reporter_user_id: "u-demo-user",
    target_type: "post",
    target_id: "p-bt-first",
    reason: "spam",
    description: "Bu hesap sahte olabilir, kontrol eder misiniz?",
    status: "open",
    assigned_to: null,
    resolution_note: null,
    created_at: h(8),
    resolved_at: null,
  },
  {
    id: "r-2",
    reporter_user_id: "u-applicant",
    target_type: "artist",
    target_id: "a-karga",
    reason: "impersonation",
    description: "Bu profilin gerçek sanatçıya ait olduğundan emin değilim.",
    status: "resolved",
    assigned_to: "u-demo-mod",
    resolution_note: "Profil doğrulama belgeleri kontrol edildi; hesap resmî.",
    created_at: d(6),
    resolved_at: d(5),
  },
];

/* ---------- Audit log ---------- */

export const demoAuditLogs: AuditLog[] = [
  {
    id: "al-1",
    actor_user_id: "u-demo-admin",
    actor_role: "super_admin",
    action: "artist_application.approved",
    target_type: "artist_application",
    target_id: "app-beton",
    previous_data: { status: "under_review" },
    new_data: { status: "approved", artist_id: "a-beton" },
    request_id: "req-demo-1",
    ip_hash: "hash:demo",
    created_at: d(9),
  },
  {
    id: "al-2",
    actor_user_id: "u-demo-mod",
    actor_role: "moderator",
    action: "report.resolved",
    target_type: "report",
    target_id: "r-2",
    previous_data: { status: "open" },
    new_data: { status: "resolved" },
    request_id: "req-demo-2",
    ip_hash: "hash:demo",
    created_at: d(5),
  },
  {
    id: "al-3",
    actor_user_id: "u-demo-admin",
    actor_role: "super_admin",
    action: "feature_flag.updated",
    target_type: "system_settings",
    target_id: null,
    previous_data: { audio_teasers_enabled: false },
    new_data: { audio_teasers_enabled: true },
    request_id: "req-demo-3",
    ip_hash: "hash:demo",
    created_at: d(12),
  },
];

/* ---------- Bildirimler ---------- */

export const demoNotifications: Notification[] = [
  {
    id: "n-1",
    recipient_user_id: "u-demo-user",
    notification_type: "artist_new_post",
    artist_id: "a-rayvold",
    post_id: "p-rv-teaser",
    title: "Ray Vold yeni bir ses önizlemesi paylaştı",
    body: "『GECE TRAFİĞİ』 intro — 30 saniyelik önizleme",
    action_url: "/sanatci/rayvold",
    is_read: false,
    read_at: null,
    created_at: h(22),
  },
  {
    id: "n-2",
    recipient_user_id: "u-demo-user",
    notification_type: "artist_countdown_started",
    artist_id: "a-semak",
    post_id: "p-sk-countdown",
    title: "Sema K bir geri sayım başlattı",
    body: "『KIYI』 — ilk albüm",
    action_url: "/sanatci/sema-k",
    is_read: false,
    read_at: null,
    created_at: d(3),
  },
  {
    id: "n-3",
    recipient_user_id: "u-demo-user",
    notification_type: "system_announcement",
    artist_id: null,
    post_id: null,
    title: "RapLab'e hoş geldin",
    body: "Takip ettiğin sanatçıların paylaşımları ana akışında görünecek.",
    action_url: "/",
    is_read: true,
    read_at: d(100),
    created_at: d(119),
  },
];

/* ---------- Özellik bayrakları ---------- */

export const demoFeatureFlags: FeatureFlags = {
  artist_applications_enabled: true,
  new_registrations_enabled: true,
  audio_teasers_enabled: true,
  video_uploads_enabled: true,
  scheduled_posts_enabled: true,
  maintenance_mode: false,
  public_follower_counts: true,
  public_like_counts: true,
  artist_custom_themes: true,
};
